---
title: "pk_lm"
author: "ss"
date: "2024-09-27"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tinytex)
data <- read_csv("pk_data_R.csv")
View(data)

library(wCorr)

cor(data$Shot_prop,data$conversion_rate,method="spearman")
weightedCorr(data$Shot_prop,data$conversion_rate,method="Pearson",weights=data$conversion_rate)       


ggplot(data=data,aes(x=conversion_rate,y=Shot_prop))+geom_smooth(method="lm",formula=y~I(x^2))

summary(lm(I(log(Shot_prop))~I(log(conversion_rate))+I(log(.1+prop_nc_missed)),data=data))

data_lm <- read_csv("pk_data_shotlevel_chrono.csv")
pk_lm1 <- lm(prop_shots_other~prop_nc_missed_other+conversion_rate_other,data=data_lm)
pk_lm2 <- lm(I(log(prop_shots_other))~I(log(1+prop_nc_missed_other))+I(log(conversion_rate_other)),data=data_lm)

pk_lm3 <- lm(prop_shots_other~prop_nc_missed_other+conversion_rate_other+I(conversion_rate_other^2),data=data_lm)
library(rgl)
plot3d(data_lm$prop_nc_missed_other,data_lm$conversion_rate_other,data_lm$prop_shots_other,data=data_lm)

library(tidyverse)
library(plotly)
library(plot3D)

# surf3D(as.matrix(lm_data$prop_nc_missed_other),as.matrix(lm_data$conversion_rate_other),as.matrix(lm_data$prop_shots_other))
# 
# fig <- plot_ly(data=lm_dat,x=~prop_nc_missed_other,y=~conversion_rate_other,z=~prop_shots_other) 
# 
# fig <- add_trace(p=fig,z=lm_dat$prop_shots_other,x=lm_dat$prop_nc_missed_other,y=lm_dat$conversion_rate_other,type="surface")
# fig
# 
# fig %>%  add_trace(p = iris_plot,
#                        z = petal_lm_surface,
#                        x = axis_x,
#                        y = axis_y,
#                        type = "surface")
# 
# fig %>% add_surface()
# fig
summary(data_lm$prop_shots_other)

summary(pk_lm1)
summary(pk_lm2)
summary(pk_lm3)
library(stargazer)
stargazer(pk_lm1,pk_lm2,pk_lm3)
```

```{r}
library(stargazer)
stargazer(pk_lm1,pk_lm2,pk_lm3)

```

